name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://truemanburbank.github.io""
author: "야간 비행"

# Disqus config
disqus-shortname: ""

# Plugins (previously gems:)
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-paginate